export const pageActionTypes = {
    ADD_TAIL_IN_FLIGHT: '[Tail] add tail in flight',
    INC_TIME: '[Time] increment time',
    DEC_TIME: '[Time] decrement time',
    GENERATE_ORDERS: '[Orders] generate orders',
    ADD_ORDER: '[Order] add order to flight',
    ADD_FLIGHT: '[Flight] add flight',
    ADD_EMPTY_FLIGHT: '[Flight] add empty flight',
    ADD_APPROACH_FLIGHT: '[Flight] add approach flight',
    REMOVE_FLIGHT: '[Flight] remove flight',
    CHECK_MONEY: '[Money] check money',
    CREATE_FLIGHT_FROM_ORDER: '[Flight] create flight from order',
    ADD_LICENCE: '[Licence] add licence',
    ADD_TAIL: '[Tail] add tail',
    ADD_ACHIEVEMENT: '[Achievement] add achievement',
  } 